name: Deploy to Heroku

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10  

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Login to Heroku
        run: |
          echo ${{ secrets.HEROKU_API_KEY }} | heroku auth:token
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}

      - name: Deploy to Heroku
        run: |
          heroku git:remote -a your-heroku-app-name
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/your-heroku-app-name.git main
